import { builtinModules } from "node:module";

import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  // General options
  bundle: true,
  // Input
  entryPoints: ["src/main.ts"],
  // Output contents
  banner: { js: banner },
  format: "cjs",
  // Output locations
  outfile: "dist/main.js",
  // Path resolution
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  // Transformation
  target: "es2018",
  // Optimization
  minify: prod,
  treeShaking: true,
  // Source maps
  sourcemap: prod ? false : "inline",
  // Logging
  logLevel: "info",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
